# Generated by Django 4.1.2 on 2022-10-28 09:49

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_document',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='search_index_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
